In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"E:\ML\Rice\Chevron_2021_Datathon_Challenge\filesForStartOfDatathon\training.csv")

In [4]:
month = []
for row in df['dayOfTheYear']:
        if  row >= 1 and row <32 :  month.append('January') 
        elif row >= 32 and row <60 :  month.append('February')
        elif row >= 60 and row <91 :  month.append('March')
        elif row >= 91 and row <121 :  month.append('April')
        elif row >= 121 and row <152 :  month.append('May')
        elif row >= 152 and row <182 :  month.append('June')
        elif row >= 182 and row <213 :  month.append('July')
        elif row >= 213 and row <244 :  month.append('August')
        elif row >= 244 and row <274:  month.append('September')
        elif row >= 274 and row <305 :  month.append('October')
        elif row >= 305 and row <335 :  month.append('November')
        elif row >= 335 and row <366 :  month.append('December')
        
        
        else:month.append('')

In [5]:
month = pd.Series(month)
df["Month"] = month.values

In [6]:
df.head()

StoreNumber  dayOfTheYear  3HourBucket  GrossSoldQuantity  \
0         1000             1            1                  3   
1         1000             1            2                  5   
2         1000             1            3                  6   
3         1000             1            4                  3   
4         1000             2            1                 13   

   Cash/Credit Site  EBT Site  Loyalty Site  ExtraMile Site CoBrand  Alcohol  \
0             False      True          True            True      No     True   
1             False      True          True            True      No     True   
2             False      True          True            True      No     True   
3             False      True          True            True      No     True   
4             False      True          True            True      No     True   

   Carwash  Food Service     City State    Month  
0    False          True  HOUSTON    TX  January  
1    False          True  HOUSTON    TX  January  
2    False          True  HOUSTON    TX  January  
3    False          True  HOUSTON    TX  January  
4    False          True  HOUSTON    TX  January

In [7]:
Weekend=[]
for row in df['dayOfTheYear']:        
    if row%7==2 or row%7==3 or row%7==4:Weekend.append(1)
    else:Weekend.append(0)

In [8]:
weekend = pd.Series(Weekend)
df["WeekEnd"] = weekend.values

In [9]:
df.head()

StoreNumber  dayOfTheYear  3HourBucket  GrossSoldQuantity  \
0         1000             1            1                  3   
1         1000             1            2                  5   
2         1000             1            3                  6   
3         1000             1            4                  3   
4         1000             2            1                 13   

   Cash/Credit Site  EBT Site  Loyalty Site  ExtraMile Site CoBrand  Alcohol  \
0             False      True          True            True      No     True   
1             False      True          True            True      No     True   
2             False      True          True            True      No     True   
3             False      True          True            True      No     True   
4             False      True          True            True      No     True   

   Carwash  Food Service     City State    Month  WeekEnd  
0    False          True  HOUSTON    TX  January        0  
1    False          True  HOUSTON    TX  January        0  
2    False          True  HOUSTON    TX  January        0  
3    False          True  HOUSTON    TX  January        0  
4    False          True  HOUSTON    TX  January        1

In [10]:
Season=[]
for row in df['Month']:

    if row=='January' or row=='February' or row=='December':Season.append('Winter')

    elif row=='March' or row=='April'or row=='May':Season.append('Spring')

    elif row=='June' or row=='July' or row=='August' :Season.append('Summer')
 
    elif row=='September' or row=='October' or row=='November' :Season.append('Autumn')
  
    else:Season.append('')


In [11]:
season = pd.Series(Season)
df["Season"] = season.values

In [12]:
df.head()

StoreNumber  dayOfTheYear  3HourBucket  GrossSoldQuantity  \
0         1000             1            1                  3   
1         1000             1            2                  5   
2         1000             1            3                  6   
3         1000             1            4                  3   
4         1000             2            1                 13   

   Cash/Credit Site  EBT Site  Loyalty Site  ExtraMile Site CoBrand  Alcohol  \
0             False      True          True            True      No     True   
1             False      True          True            True      No     True   
2             False      True          True            True      No     True   
3             False      True          True            True      No     True   
4             False      True          True            True      No     True   

   Carwash  Food Service     City State    Month  WeekEnd  Season  
0    False          True  HOUSTON    TX  January        0  Winter  
1    False          True  HOUSTON    TX  January        0  Winter  
2    False          True  HOUSTON    TX  January        0  Winter  
3    False          True  HOUSTON    TX  January        0  Winter  
4    False          True  HOUSTON    TX  January        1  Winter

In [13]:
Day_Of_The_Week=[]
for row in df['dayOfTheYear']:
    if row%7==1 :Day_Of_The_Week.append(4)
    elif row%7==2 :Day_Of_The_Week.append(5)
    elif row%7==3 :Day_Of_The_Week.append(6)
    elif row%7==4 :Day_Of_The_Week.append(7)
    elif row%7==5 :Day_Of_The_Week.append(1)
    elif row%7==6 :Day_Of_The_Week.append(2)
    elif row%7==0 :Day_Of_The_Week.append(3)

In [14]:
dotw = pd.Series(Day_Of_The_Week)
df["dayOfTheWeek"] = dotw.values

In [15]:
df.head()

StoreNumber  dayOfTheYear  3HourBucket  GrossSoldQuantity  \
0         1000             1            1                  3   
1         1000             1            2                  5   
2         1000             1            3                  6   
3         1000             1            4                  3   
4         1000             2            1                 13   

   Cash/Credit Site  EBT Site  Loyalty Site  ExtraMile Site CoBrand  Alcohol  \
0             False      True          True            True      No     True   
1             False      True          True            True      No     True   
2             False      True          True            True      No     True   
3             False      True          True            True      No     True   
4             False      True          True            True      No     True   

   Carwash  Food Service     City State    Month  WeekEnd  Season  \
0    False          True  HOUSTON    TX  January        0  Winter   
1    False          True  HOUSTON    TX  January        0  Winter   
2    False          True  HOUSTON    TX  January        0  Winter   
3    False          True  HOUSTON    TX  January        0  Winter   
4    False          True  HOUSTON    TX  January        1  Winter   

   dayOfTheWeek  
0             4  
1             4  
2             4  
3             4  
4             5

In [16]:
df.nunique()

StoreNumber            4
dayOfTheYear         363
3HourBucket            4
GrossSoldQuantity    119
Cash/Credit Site       1
EBT Site               2
Loyalty Site           1
ExtraMile Site         1
CoBrand                1
Alcohol                2
Carwash                2
Food Service           1
City                   4
State                  1
Month                 12
WeekEnd                2
Season                 4
dayOfTheWeek           7
dtype: int64

In [17]:
df = df.drop(["Cash/Credit Site" , "Loyalty Site" , "ExtraMile Site" , "Food Service" , "CoBrand"] , axis = 1)

In [18]:
df = df.drop(["State"] , axis=1)

In [19]:
target = df["GrossSoldQuantity"]
train = df.drop(["GrossSoldQuantity"] , axis=1)

In [20]:
target = target.values.reshape(-1 , 1)

In [21]:
train = train.drop(["StoreNumber"] , axis=1)

In [22]:
train_copy = train.copy()

In [23]:
train_copy

dayOfTheYear  3HourBucket  EBT Site  Alcohol  Carwash         City  \
0                1            1      True     True    False      HOUSTON   
1                1            2      True     True    False      HOUSTON   
2                1            3      True     True    False      HOUSTON   
3                1            4      True     True    False      HOUSTON   
4                2            1      True     True    False      HOUSTON   
...            ...          ...       ...      ...      ...          ...   
5655           362            2     False    False     True  SAN ANTONiO   
5656           362            3     False    False     True  SAN ANTONiO   
5657           362            4     False    False     True  SAN ANTONiO   
5658           363            3     False    False     True  SAN ANTONiO   
5659           363            4     False    False     True  SAN ANTONiO   

         Month  WeekEnd  Season  dayOfTheWeek  
0      January        0  Winter             4  
1      January        0  Winter             4  
2      January        0  Winter             4  
3      January        0  Winter             4  
4      January        1  Winter             5  
...        ...      ...     ...           ...  
5655  December        0  Winter             1  
5656  December        0  Winter             1  
5657  December        0  Winter             1  
5658  December        0  Winter             2  
5659  December        0  Winter             2  

[5660 rows x 10 columns]

In [24]:
#train_copy = train_copy.drop(["dayOfTheYear"] , axis=1)

In [25]:
train_copy

dayOfTheYear  3HourBucket  EBT Site  Alcohol  Carwash         City  \
0                1            1      True     True    False      HOUSTON   
1                1            2      True     True    False      HOUSTON   
2                1            3      True     True    False      HOUSTON   
3                1            4      True     True    False      HOUSTON   
4                2            1      True     True    False      HOUSTON   
...            ...          ...       ...      ...      ...          ...   
5655           362            2     False    False     True  SAN ANTONiO   
5656           362            3     False    False     True  SAN ANTONiO   
5657           362            4     False    False     True  SAN ANTONiO   
5658           363            3     False    False     True  SAN ANTONiO   
5659           363            4     False    False     True  SAN ANTONiO   

         Month  WeekEnd  Season  dayOfTheWeek  
0      January        0  Winter             4  
1      January        0  Winter             4  
2      January        0  Winter             4  
3      January        0  Winter             4  
4      January        1  Winter             5  
...        ...      ...     ...           ...  
5655  December        0  Winter             1  
5656  December        0  Winter             1  
5657  December        0  Winter             1  
5658  December        0  Winter             2  
5659  December        0  Winter             2  

[5660 rows x 10 columns]

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [27]:
train_copy = train_copy.apply(le.fit_transform)

In [28]:
train_copy.head()

dayOfTheYear  3HourBucket  EBT Site  Alcohol  Carwash  City  Month  \
0             0            0         1        1        0     2      4   
1             0            1         1        1        0     2      4   
2             0            2         1        1        0     2      4   
3             0            3         1        1        0     2      4   
4             1            0         1        1        0     2      4   

   WeekEnd  Season  dayOfTheWeek  
0        0       3             3  
1        0       3             3  
2        0       3             3  
3        0       3             3  
4        1       3             4

In [42]:
cat=['3HourBucket', 'EBT Site', 'Alcohol', 'Carwash', 'City','Month', 'WeekEnd', 'Season', 'dayOfTheWeek']

In [61]:
import xgboost as xgb
model = xgb.XGBRegressor(max_depth=4,
    learning_rate=0.05,
    n_estimators=1000,
    verbosity=2,
    silent=None,
    objective='reg:linear',
    booster='gbtree',
    n_jobs=-1,
    nthread=None,
    gamma=0.5,
    min_child_weight=2,
    max_delta_step=0,
    subsample=0.7,
    colsample_bytree=1,
    colsample_bylevel=1,
    colsample_bynode=1,
    reg_alpha=0,
    reg_lambda=1,
    scale_pos_weight=1,
    base_score=0.5,
    random_state=0,
    seed=None)

In [30]:
from sklearn.model_selection import train_test_split as split
x_train , x_test , y_train , y_test = split(train_copy , target , test_size=0.2 , stratify=train_copy["City"] , random_state=42)

In [62]:
model.fit(x_train , y_train , eval_set = [(x_test , y_test)] , early_stopping_rounds=40 , verbose = 10)

[02:07:29] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 28 extra nodes, 0 pruned nodes, max_depth=4
[0]	validation_0-rmse:30.23192
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 28 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 28 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101:

[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 

[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 

[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[150]	validation_0-rmse:9.73346
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 28 extra nodes, 2 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree

[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 28 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 28 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[200]	validation_0-rmse:9.70429
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree

[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[250]	validation_0-rmse:9.69584
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 24 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 28 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 30 extra nodes, 0 pruned nodes, max_depth=4
[02:07:29] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0.5, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.05, max_delta_step=0, max_depth=4,
             min_child_weight=2, missing=nan, monotone_constraints='()',
             n_estimators=1000, n_jobs=-1, nthread=12, num_parallel_tree=1,
             objective='reg:linear', random_state=0, reg_alpha=0, reg_lambda=1,
             scale_pos_weight=1, seed=0, silent=None, subsample=0.7,
             tree_method='exact', validate_parameters=1, verbosity=2)

In [58]:
params={"learning_rate"    : [0.05,0.1,0.2 ] ,
 "min_child_weight" : [ 1,2 ],
 "gamma"            : [ 0.4,0.5,0.6],
 "colsample_bytree" : [  0.5 , 0.6 ] }

In [59]:
from sklearn.model_selection import GridSearchCV
gsearch = GridSearchCV(estimator = model,
                           param_grid = params,                        
                           cv = 5,
                           n_jobs = -1,
                           verbose = 1)

gsearch.fit(x_train , y_train , eval_set = [(x_test , y_test)] , early_stopping_rounds=40 , verbose = 10)



Fitting 5 folds for each of 36 candidates, totalling 180 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    5.6s


[02:06:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 66 extra nodes, 4 pruned nodes, max_depth=8
[0]	validation_0-rmse:30.33904
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 68 extra nodes, 0 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 154 extra nodes, 0 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 192 extra nodes, 0 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:10

[Parallel(n_jobs=-1)]: Done 180 out of 180 | elapsed:   34.9s finished


[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 348 extra nodes, 2 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 260 extra nodes, 4 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 46 extra nodes, 4 pruned nodes, max_depth=6
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 148 extra nodes, 8 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 368 extra nodes, 4 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 48 extra nodes

[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 238 extra nodes, 0 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 186 extra nodes, 14 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 52 extra nodes, 0 pruned nodes, max_depth=6
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 272 extra nodes, 4 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 260 extra nodes, 4 pruned nodes, max_depth=8
[02:06:21] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 292 extra nod

[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 76 extra nodes, 2 pruned nodes, max_depth=8
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 168 extra nodes, 22 pruned nodes, max_depth=8
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 246 extra nodes, 0 pruned nodes, max_depth=8
[150]	validation_0-rmse:9.72179
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 178 extra nodes, 4 pruned nodes, max_depth=8
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 160 extra nodes, 10 pruned nodes, max_depth=8
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101

[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 210 extra nodes, 12 pruned nodes, max_depth=8
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 306 extra nodes, 0 pruned nodes, max_depth=8
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 156 extra nodes, 4 pruned nodes, max_depth=8
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 266 extra nodes, 8 pruned nodes, max_depth=8
[200]	validation_0-rmse:9.74138
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101: tree pruning end, 214 extra nodes, 0 pruned nodes, max_depth=8
[02:06:22] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/tree/updater_prune.cc:101

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=0.5, booster='gbtree',
                                    colsample_bylevel=1, colsample_bynode=1,
                                    colsample_bytree=1, gamma=0, gpu_id=-1,
                                    importance_type='gain',
                                    interaction_constraints='',
                                    learning_rate=0.1, max_delta_step=0,
                                    max_depth=8, min_child_weight=1,
                                    missing=nan, monotone_constraints='()',
                                    n_estimators=1000, n_jobs=-1, nthread=12,
                                    num_parallel_tree=1, objective='reg:linear',
                                    random_state=0, reg_alpha=0, reg_lambda=1,
                                    scale_pos_weight=1, seed=0, silent=None,
                                    subsample=0.7, tree_method='exact',
                             

In [60]:
gsearch.best_params_

{'colsample_bytree': 0.5,
 'gamma': 0.5,
 'learning_rate': 0.05,
 'min_child_weight': 2}

In [63]:
preds = model.predict(x_test)

In [33]:
y_test

array([[19],
       [29],
       [35],
       ...,
       [ 8],
       [37],
       [63]], dtype=int64)

In [64]:
from sklearn.metrics import mean_squared_error
import math
math.sqrt(mean_squared_error(preds , y_test))

9.682851973025983

In [35]:
from scipy.spatial import distance
distance.euclidean(preds , y_test)

325.4365705542651

In [36]:
from sklearn.metrics.pairwise import euclidean_distances
preds = preds.reshape(-1 , 1)
for points in zip(preds , y_test):
    print(points)
#euclidean_distances(preds.reshape(-1 , 1) , y_test.reshape(-1 , 1))

(array([33.300846], dtype=float32), array([19], dtype=int64))
(array([35.451977], dtype=float32), array([29], dtype=int64))
(array([18.18913], dtype=float32), array([35], dtype=int64))
(array([36.532635], dtype=float32), array([32], dtype=int64))
(array([7.1637287], dtype=float32), array([9], dtype=int64))
(array([25.412045], dtype=float32), array([32], dtype=int64))
(array([7.365165], dtype=float32), array([10], dtype=int64))
(array([44.834095], dtype=float32), array([52], dtype=int64))
(array([6.5980663], dtype=float32), array([7], dtype=int64))
(array([39.57495], dtype=float32), array([32], dtype=int64))
(array([2.3706865], dtype=float32), array([1], dtype=int64))
(array([6.475055], dtype=float32), array([3], dtype=int64))
(array([24.941223], dtype=float32), array([24], dtype=int64))
(array([5.379133], dtype=float32), array([4], dtype=int64))
(array([41.37726], dtype=float32), array([48], dtype=int64))
(array([35.258194], dtype=float32), array([76], dtype=int64))
(array([19.701168],

(array([39.515694], dtype=float32), array([20], dtype=int64))
(array([2.6687255], dtype=float32), array([8], dtype=int64))
(array([5.53248], dtype=float32), array([5], dtype=int64))
(array([6.9677334], dtype=float32), array([8], dtype=int64))
(array([54.22113], dtype=float32), array([49], dtype=int64))
(array([39.315983], dtype=float32), array([38], dtype=int64))
(array([35.57335], dtype=float32), array([5], dtype=int64))
(array([26.228344], dtype=float32), array([40], dtype=int64))
(array([17.789467], dtype=float32), array([23], dtype=int64))
(array([25.541267], dtype=float32), array([55], dtype=int64))
(array([41.107666], dtype=float32), array([39], dtype=int64))
(array([41.80694], dtype=float32), array([65], dtype=int64))
(array([66.716354], dtype=float32), array([101], dtype=int64))
(array([11.476041], dtype=float32), array([15], dtype=int64))
(array([2.0744948], dtype=float32), array([2], dtype=int64))
(array([27.871323], dtype=float32), array([28], dtype=int64))
(array([37.662766

In [39]:
preds = np.round(preds)

In [40]:
preds

array([[33.],
       [35.],
       [18.],
       ...,
       [ 8.],
       [39.],
       [54.]], dtype=float32)